spawner-range: 40
booster-duration: 12 hours
booster-multiplier: 2

booster-item:
  type: ALLAY_SPAWN_EGG
  name: "&e&lSPAWNER BOOSTER"
  lore:
      - "&7Consumable"
      - "&7a Lasts &e&l%duration%"
sell-wand-item:
  type: STICK
  name: "&e&lSELL WAND"
  lore:
    - "&7Right click to sell all items in the spawners around you"

pickaxe:
  multi-pick: true # if true, any pickaxe can break spawners
  types: # Pickaxe types that can break spawners
    - DIAMOND_PICKAXE
    - IRON_PICKAXE
can-pickup-at-zero: false